const data = {
  products: [
    {
      name: 'silver Full Rim Rectangle Eyeglasses',
      slug: 'silver Full Rim Rectangle Eyeglasses',
      category: 'Transparent',
      image: '/images/p1.jpg', //
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality eyeglass',
    },
    {
      name: ' Transparent Full Rim Square Eyeglasses',
      slug: ' Transparent Full Rim Square Eyeglasses',
      category: 'Transparent',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Air Signia',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: '',
      slug: 'Blue Transparent Full Rim Square Eyeglasses',
      category: 'Transparent',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Air Signia',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Purple Transparent Full Rim Square Eyeglasses',
      slug: 'Purple Transparent Full Rim Square Eyeglasses',
      category: 'Transparent',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Air Signia',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Red Transparent Full Rim Square Eyeglasses',
      slug: 'Red Transparent Full Rim Square Eyeglasses',
      category: 'Transparent',
      image: '/images/p6.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Air Signia',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
